// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace LocationLocation.iOS
{
	public partial class DetailViewController : UIViewController
	{
		public DetailViewController (IntPtr handle) : base (handle)
		{
		}

		public DetailViewController () : base("DetailViewController", null)
		{

		}
	}
}
